# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1iGl5QYR8fE3p-ceJbppuiDkBmZDbOK
"""

!pip install streamlit plotly

import pandas as pd

# Base URL for the Economic Tracker raw CSV files
base_url = "https://raw.githubusercontent.com/OpportunityInsights/EconomicTracker/main/data/"

# Load consumer spending data (daily, by state)
spending = pd.read_csv(base_url + "Affinity%20-%20State%20-%20Daily.csv")

# Load employment data (weekly, by state)
employment = pd.read_csv(base_url + "Employment%20-%20State%20-%20Weekly.csv")

# Load geographic crosswalk (state FIPS codes to state names)
geo = pd.read_csv(base_url + "GeoIDs%20-%20State.csv")

# Create a proper datetime column from year, month, and day
spending["date"] = pd.to_datetime(
    spending[["year", "month", "day"]].rename(columns={"day": "day"})
)

# Filter to the 2020-2023 recovery period
spending = spending[(spending["date"] >= "2020-01-01") & (spending["date"] <= "2023-12-31")]

# Select key columns for analysis
spending = spending[["statefips", "date", "spend_all", "spend_all_q1", "spend_all_q2", "spend_all_q3", "spend_all_q4"]]

print(f"Spending data: {spending.shape[0]} rows, {spending.shape[1]} columns")
print(f"Date range: {spending['date'].min()} to {spending['date'].max()}")
spending.head()

# Create a datetime column from year, month, and day_endofweek
employment["date"] = pd.to_datetime(
    employment["year"].astype(str) + "-" + employment["month"].astype(str) + "-" + employment["day_endofweek"].astype(str)
)

# Filter to the same 2020-2023 period
employment = employment[(employment["date"] >= "2020-01-01") & (employment["date"] <= "2023-12-31")]

# Select key columns for analysis
employment = employment[["statefips", "date", "emp", "emp_incq1", "emp_incq2", "emp_incq3", "emp_incq4"]]

print(f"Employment data: {employment.shape[0]} rows, {employment.shape[1]} columns")
print(f"Date range: {employment['date'].min()} to {employment['date'].max()}")
employment.head()

# 1. Convert spending columns to numeric FIRST
spending_cols = ["spend_all", "spend_all_q1", "spend_all_q2", "spend_all_q3", "spend_all_q4"]
for col in spending_cols:
    spending[col] = pd.to_numeric(spending[col], errors="coerce")

# 2. Resample spending from daily to Sunday-ending weekly averages
spending_weekly = spending.groupby([pd.Grouper(key="date", freq="W"), "statefips"]).agg(
    spend_all=("spend_all", "mean"),
    spend_all_q1=("spend_all_q1", "mean"),
    spend_all_q2=("spend_all_q2", "mean"),
    spend_all_q3=("spend_all_q3", "mean"),
    spend_all_q4=("spend_all_q4", "mean"),
).reset_index()

# 3. ALIGNMENT FIX: Snap employment dates to the upcoming Sunday boundaries
employment["date"] = employment["date"] + pd.to_timedelta(6 - employment["date"].dt.weekday, unit="D")

# 4. Merge spending and employment on date and statefips
merged = spending_weekly.merge(
    employment,
    on=["date", "statefips"],
    how="inner"
)

# 5. Add human-readable state names from the GeoIDs crosswalk
merged = merged.merge(
    geo[["statefips", "statename"]],
    on="statefips",
    how="left"
)

# 6. Convert employment columns to numeric, coercing '.' and empty strings to NaN
employment_cols = ["emp", "emp_incq1", "emp_incq2", "emp_incq3", "emp_incq4"]
for col in employment_cols:
    merged[col] = pd.to_numeric(merged[col], errors="coerce")

print(f"Merged data: {merged.shape[0]} rows, {merged.shape[1]} columns")
print(f"Date range: {merged['date'].min()} to {merged['date'].max()}")
print(f"Null state names: {merged['statename'].isna().sum()}")
print(f"States included: {merged['statename'].nunique()}")
merged.head()

# Resample spending from daily to weekly to align with employment data
spending_weekly = spending.groupby([pd.Grouper(key="date", freq="W"), "statefips"]).agg(
    spend_all=("spend_all", "mean"),
    spend_all_q1=("spend_all_q1", "mean"),
    spend_all_q2=("spend_all_q2", "mean"),
    spend_all_q3=("spend_all_q3", "mean"),
    spend_all_q4=("spend_all_q4", "mean"),
).reset_index()

# Merge spending and employment on date and state
merged = spending_weekly.merge(
    employment,
    on=["date", "statefips"],
    how="inner"
)

# Add human-readable state names from the GeoIDs crosswalk
merged = merged.merge(
    geo[["statefips", "statename"]],
    on="statefips",
    how="left"
)

# Convert columns to numeric, coercing '.' and empty strings to NaN
numeric_cols = ["spend_all", "spend_all_q1", "spend_all_q2", "spend_all_q3", "spend_all_q4",
                "emp", "emp_incq1", "emp_incq2", "emp_incq3", "emp_incq4"]
for col in numeric_cols:
    merged[col] = pd.to_numeric(merged[col], errors="coerce")

print(f"Merged data: {merged.shape[0]} rows, {merged.shape[1]} columns")
print(f"Date range: {merged['date'].min()} to {merged['date'].max()}")
print(f"Null state names: {merged['statename'].isna().sum()}")
print(f"States included: {merged['statename'].nunique()}")
merged.head()

import plotly.express as px
import plotly.graph_objects as go

# Calculate average spending recovery per state (2021-2022 period)
recovery_period = merged[(merged["date"] >= "2021-01-01") & (merged["date"] <= "2022-12-31")]

state_metrics = recovery_period.groupby("statename").agg(
    avg_spend_recovery=("spend_all", "mean"),
    avg_emp_recovery=("emp", "mean"),
    q4_recovery=("spend_all_q4", "mean"),
    q1_recovery=("spend_all_q1", "mean"),
).reset_index()

# Calculate income inequality gap (Q4 highest-income minus Q1 lowest-income recovery)
state_metrics["income_inequality_gap"] = state_metrics["q4_recovery"] - state_metrics["q1_recovery"]

print(state_metrics[["statename", "avg_spend_recovery", "avg_emp_recovery", "income_inequality_gap"]].head(10))
print(f"\nTotal states analyzed: {len(state_metrics)}")

# Calculate employment recovery timeline (weeks to return to pre-pandemic baseline)
# Baseline is 0% change (the January 2020 reference point)
emp_by_state_week = merged.groupby(["statename", "date"])["emp"].mean().reset_index()
emp_by_state_week["recovered"] = emp_by_state_week["emp"] >= 0

def weeks_to_recover(group):
    """Find how many weeks it took for employment to first reach baseline."""
    recovered_rows = group[group["recovered"]]
    if recovered_rows.empty:
        return None
    first_recovery_date = recovered_rows["date"].min()
    pandemic_start = pd.Timestamp("2020-03-15")
    return (first_recovery_date - pandemic_start).days // 7

# Apply the function to each state
recovery_timeline = emp_by_state_week.groupby("statename").apply(weeks_to_recover).reset_index()
recovery_timeline.columns = ["statename", "weeks_to_recover"]

# Merge into state metrics
state_metrics = state_metrics.merge(recovery_timeline, on="statename", how="left")

print(state_metrics[["statename", "weeks_to_recover"]].sort_values("weeks_to_recover").head(10))
print(f"\nStates that never fully recovered: {state_metrics['weeks_to_recover'].isna().sum()}")

# Line chart: National spending recovery over time, split by income quartile
national = merged.groupby("date").agg(
    Q1=("spend_all_q1", "mean"),
    Q2=("spend_all_q2", "mean"),
    Q3=("spend_all_q3", "mean"),
    Q4=("spend_all_q4", "mean"),
).reset_index()

fig_quartile = go.Figure()
for quartile in ["Q1", "Q2", "Q3", "Q4"]:
    fig_quartile.add_trace(go.Scatter(
        x=national["date"],
        y=national[quartile],
        mode="lines",
        name=f"Income {quartile}"
    ))
fig_quartile.update_layout(
    title="National Spending Recovery by Income Quartile",
    yaxis_title="Spending Change (relative to Jan 2020)",
    xaxis_title="Date",
    hovermode="x unified"
)
fig_quartile.show()

"""## Key Finding 1: Income Quartile Recovery Gap

The spending recovery after the 2020 downturn was deeply unequal across income groups.
The highest-income quartile (Q4) recovered to and exceeded baseline spending levels
faster than the lowest-income quartile (Q1), which experienced a prolonged period of
reduced spending.

This gap persisted throughout 2021-2022, suggesting structural barriers to recovery
for lower-income households rather than a temporary shock.
"""

# Bar chart: Top 20 states ranked by overall spending recovery speed
state_recovery_sorted = state_metrics.sort_values("avg_spend_recovery", ascending=True).tail(20)

fig_states = px.bar(
    state_recovery_sorted,
    x="avg_spend_recovery",
    y="statename",
    orientation="h",
    title="Top 20 States by Average Spending Recovery",
    labels={"avg_spend_recovery": "Avg Spending Change", "statename": "State"}
)
fig_states.show()

"""## Key Finding 2: State-Level Recovery Varies Widely

Not all states recovered at the same pace. States with diversified economies and
higher remote-work adoption tended to recover consumer spending faster. States
heavily dependent on tourism, hospitality, or energy sectors showed slower recovery
trajectories.

The top-recovering states consistently outperformed the national average by a
significant margin, while lagging states remained below baseline for extended periods.
"""

# Scatter plot: Spending recovery vs employment recovery per state
fig_scatter = px.scatter(
    state_metrics,
    x="avg_spend_recovery",
    y="avg_emp_recovery",
    text="statename",
    title="Spending Recovery vs Employment Recovery",
    labels={"avg_spend_recovery": "Avg Spending Recovery", "avg_emp_recovery": "Avg Employment Recovery"}
)
fig_scatter.update_traces(textposition="top center", textfont_size=8)
fig_scatter.show()

"""## Key Finding 3: Spending and Employment Don't Always Move Together

The scatter plot reveals that spending recovery and employment recovery are
correlated but not identical. Some states saw consumer spending rebound while
employment remained depressed, likely due to government transfer payments and
changes in spending patterns (e.g., goods vs. services).

Other states recovered employment but saw muted spending growth, possibly
reflecting jobs returning at lower wages or in different sectors than pre-pandemic.

**Recommendation:** Policymakers and businesses should track both metrics
together rather than relying on a single indicator to gauge economic health.
"""

